[project]
name = "hello-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "agents>=1.4.0",
    "chainlit>=0.1.0",
    "dotenv>=0.9.9",
    "openai[agents]>=0.8.0",
    "tensorflow-probability>=0.19.0",
]
